car:
  max_speed: 400
  
imu:
  accelerometer_noise_density: 2.0000e-3  
  accelerometer_random_walk: 3.0000e-3    
  gyroscope_noise_density: 1.6968e-04     
  gyroscope_random_walk: 1.9393e-05  

ekf:
  measurement_covariance_matrix:
    - [1, 0, 0]
    - [0, 1, 0]
    - [0, 0, 1]

  prediction_covariance_matrix:
    - [1, 0, 0]
    - [0, 1, 0]
    - [0, 0, 1] 

  